## Summarizing categorical data using pandas

In [1]:
import numpy as np
import pandas as pd

### The basics

In [2]:
address = '../data/mtcars.csv'

cars = pd.read_csv(address)
cars.columns = ['car_names','mpg','cyl','disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']
cars.index = cars.car_names

In [3]:
carb = cars.carb
carb.value_counts()

carb
4    10
2    10
1     7
3     3
6     1
8     1
Name: count, dtype: int64

In [5]:
cars_cat = cars[['cyl', 'vs', 'am', 'gear', 'carb']]
cars_cat.head()

                   cyl  vs  am  gear  carb
car_names
Mazda RX4            6   0   1     4     4
Mazda RX4 Wag        6   0   1     4     4
Datsun 710           4   1   1     4     1
Hornet 4 Drive       6   1   0     3     1
Hornet Sportabout    8   0   0     3     2

In [6]:
gears_group = cars_cat.groupby('gear')
gears_group.describe()

       cyl                                                 vs            ...  \
     count      mean       std  min  25%  50%  75%  max count      mean  ...
gear                                                                     ...
3     15.0  7.466667  1.187234  4.0  8.0  8.0  8.0  8.0  15.0  0.200000  ...
4     12.0  4.666667  0.984732  4.0  4.0  4.0  6.0  6.0  12.0  0.833333  ...
5      5.0  6.000000  2.000000  4.0  4.0  6.0  8.0  8.0   5.0  0.200000  ...

       am       carb
      75%  max count      mean       std  min  25%  50%  75%  max
gear
3     0.0  0.0  15.0  2.666667  1.175139  1.0  2.0  3.0  4.0  4.0
4     1.0  1.0  12.0  2.333333  1.302678  1.0  1.0  2.0  4.0  4.0
5     1.0  1.0   5.0  4.400000  2.607681  2.0  2.0  4.0  6.0  8.0

[3 rows x 32 columns]

### Transforming variables to categorical data type

In [7]:
cars['group'] = pd.Series(cars.gear, dtype='category')

In [8]:
cars['group'].dtype

CategoricalDtype(categories=[3, 4, 5], ordered=False, categories_dtype=int64)

In [9]:
cars['group'].value_counts()

group
3    15
4    12
5     5
Name: count, dtype: int64

### Describing categorical data with crosstabs

In [10]:
pd.crosstab(cars['am'], cars['gear'])

gear   3  4  5
am
0     15  4  0
1      0  8  5